// Full Azura Restaurant Menu with Images

export const fullMenuData = {
  "food": {
    "chicken-butterfly": {
      "name": "Chicken Butterfly",
      "nameAr": "Chicken Butterfly",
      "description": "",
      "descriptionAr": "",
      "price": 336,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",

    },
    "chicken-lemon-pasta": {
      "name": "Chicken Lemon Pasta",
      "nameAr": "Chicken Lemon Pasta",
      "description": "",
      "descriptionAr": "",
      "price": 234,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",

    },
    "dynamite-chicken": {
      "name": "Dynamite Chicken",
      "nameAr": "Dynamite Chicken",
      "description": "",
      "descriptionAr": "",
      "price": 178,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",

    },
    "azura-breakfast": {
      "name": "Azura Breakfast",
      "nameAr": "Azura Breakfast",
      "description": "",
      "descriptionAr": "",
      "price": 204,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&q=80",

    },
    "mexican-breakfast": {
      "name": "Mexican Breakfast",
      "nameAr": "Mexican Breakfast",
      "description": "",
      "descriptionAr": "",
      "price": 174,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",

    },
    "greek-breakfast": {
      "name": "Greek Breakfast",
      "nameAr": "Greek Breakfast",
      "description": "",
      "descriptionAr": "",
      "price": 189,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&q=80",

    },
    "triple-s": {
      "name": "Triple S",
      "nameAr": "Triple S",
      "description": "",
      "descriptionAr": "",
      "price": 218,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&q=80",

    },
    "chicken-cheese": {
      "name": "Chicken Cheese",
      "nameAr": "Chicken Cheese",
      "description": "",
      "descriptionAr": "",
      "price": 219,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&q=80",

    },
    "mix-cheese": {
      "name": "Mix Cheese",
      "nameAr": "Mix Cheese",
      "description": "",
      "descriptionAr": "",
      "price": 114,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",

    },
    "tuna": {
      "name": "Tuna",
      "nameAr": "Tuna",
      "description": "",
      "descriptionAr": "",
      "price": 194,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80",

    },
    "classic": {
      "name": "Classic",
      "nameAr": "Classic",
      "description": "",
      "descriptionAr": "",
      "price": 71,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80",

    },
    "azura-croissant": {
      "name": "Azura Croissant",
      "nameAr": "Azura Croissant",
      "description": "",
      "descriptionAr": "",
      "price": 149,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",

    },
    "tomato-and-basil-soup": {
      "name": "Tomato and Basil Soup",
      "nameAr": "Tomato and Basil Soup",
      "description": "",
      "descriptionAr": "",
      "price": 93,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&q=80",

    },
    "mushroom-cream": {
      "name": "Mushroom Cream",
      "nameAr": "Mushroom Cream",
      "description": "",
      "descriptionAr": "",
      "price": 102,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",

    },
    "creamy-chicken": {
      "name": "Creamy Chicken",
      "nameAr": "Creamy Chicken",
      "description": "",
      "descriptionAr": "",
      "price": 113,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80",

    },
    "creamy-chicken-mushroom": {
      "name": "Creamy Chicken Mushroom",
      "nameAr": "Creamy Chicken Mushroom",
      "description": "",
      "descriptionAr": "",
      "price": 149,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80",

    },
    "fries": {
      "name": "Fries",
      "nameAr": "Fries",
      "description": "",
      "descriptionAr": "",
      "price": 86,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&q=80",

    },
    "cheese-fries": {
      "name": "Cheese Fries",
      "nameAr": "Cheese Fries",
      "description": "",
      "descriptionAr": "",
      "price": 106,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400&q=80",

    },
    "beef-quesadilla": {
      "name": "Beef Quesadilla",
      "nameAr": "Beef Quesadilla",
      "description": "",
      "descriptionAr": "",
      "price": 211,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80",

    },
    "chicken-quesadilla": {
      "name": "Chicken Quesadilla",
      "nameAr": "Chicken Quesadilla",
      "description": "",
      "descriptionAr": "",
      "price": 212,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400&q=80",

    },
    "nachos": {
      "name": "Nachos",
      "nameAr": "Nachos",
      "description": "",
      "descriptionAr": "",
      "price": 128,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400&q=80",

    },
    "chicken-fries": {
      "name": "Chicken Fries",
      "nameAr": "Chicken Fries",
      "description": "",
      "descriptionAr": "",
      "price": 202,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",

    },
    "chili-texas-fries": {
      "name": "Chili Texas Fries",
      "nameAr": "Chili Texas Fries",
      "description": "",
      "descriptionAr": "",
      "price": 159,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80",

    },
    "mozzarella-steak": {
      "name": "Mozzarella Steak",
      "nameAr": "Mozzarella Steak",
      "description": "",
      "descriptionAr": "",
      "price": 96,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80",

    },
    "strips": {
      "name": "Strips",
      "nameAr": "Strips",
      "description": "",
      "descriptionAr": "",
      "price": 189,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",

    },
    "onion-rings": {
      "name": "Onion Rings",
      "nameAr": "Onion Rings",
      "description": "",
      "descriptionAr": "",
      "price": 88,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400&q=80",

    },
    "azura-plate": {
      "name": "Azura Plate",
      "nameAr": "Azura Plate",
      "description": "",
      "descriptionAr": "",
      "price": 256,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&q=80",

    },
    "baked-potato": {
      "name": "Baked Potato",
      "nameAr": "Baked Potato",
      "description": "",
      "descriptionAr": "",
      "price": 92,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&q=80",

    },
    "azura-potato": {
      "name": "Azura Potato",
      "nameAr": "Azura Potato",
      "description": "",
      "descriptionAr": "",
      "price": 123,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",

    },
    "greek-salad": {
      "name": "Greek Salad",
      "nameAr": "Greek Salad",
      "description": "",
      "descriptionAr": "",
      "price": 133,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&q=80",

    },
    "chicken-caesar-salad": {
      "name": "Chicken Caesar Salad",
      "nameAr": "Chicken Caesar Salad",
      "description": "",
      "descriptionAr": "",
      "price": 204,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&q=80",

    },
    "rocca-salad": {
      "name": "Rocca Salad",
      "nameAr": "Rocca Salad",
      "description": "",
      "descriptionAr": "",
      "price": 124,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80",

    },
    "california-salad": {
      "name": "California Salad",
      "nameAr": "California Salad",
      "description": "",
      "descriptionAr": "",
      "price": 193,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&q=80",

    },
    "azura-diso-salad": {
      "name": "Azura Diso Salad",
      "nameAr": "Azura Diso Salad",
      "description": "",
      "descriptionAr": "",
      "price": 248,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&q=80",

    },
    "tuna-salad": {
      "name": "Tuna Salad",
      "nameAr": "Tuna Salad",
      "description": "",
      "descriptionAr": "",
      "price": 206,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400&q=80",

    },
    "alfredo-pasta": {
      "name": "Alfredo Pasta",
      "nameAr": "Alfredo Pasta",
      "description": "",
      "descriptionAr": "",
      "price": 249,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400&q=80",

    },
    "negresco": {
      "name": "Negresco",
      "nameAr": "Negresco",
      "description": "",
      "descriptionAr": "",
      "price": 258,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80",

    },
    "mac-and-cheese": {
      "name": "Mac and Cheese",
      "nameAr": "Mac and Cheese",
      "description": "",
      "descriptionAr": "",
      "price": 247,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",

    },
    "pesto-pasta": {
      "name": "Pesto Pasta",
      "nameAr": "Pesto Pasta",
      "description": "",
      "descriptionAr": "",
      "price": 216,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&q=80",

    },
    "chicken-gravy-pasta": {
      "name": "Chicken Gravy Pasta",
      "nameAr": "Chicken Gravy Pasta",
      "description": "",
      "descriptionAr": "",
      "price": 206,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",

    },
    "beef-stroganoff-pasta": {
      "name": "Beef Stroganoff Pasta",
      "nameAr": "Beef Stroganoff Pasta",
      "description": "",
      "descriptionAr": "",
      "price": 279,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&q=80",

    },
    "azura-spicy-pasta": {
      "name": "Azura Spicy Pasta",
      "nameAr": "Azura Spicy Pasta",
      "description": "",
      "descriptionAr": "",
      "price": 189,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",

    },
    "pasta-arrabbiata": {
      "name": "Pasta Arrabbiata",
      "nameAr": "Pasta Arrabbiata",
      "description": "",
      "descriptionAr": "",
      "price": 165,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&q=80",

    },
    "pasta-forno": {
      "name": "Pasta Forno",
      "nameAr": "Pasta Forno",
      "description": "",
      "descriptionAr": "",
      "price": 204,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&q=80",

    },
    "spaghetti-bolognese": {
      "name": "Spaghetti Bolognese",
      "nameAr": "Spaghetti Bolognese",
      "description": "",
      "descriptionAr": "",
      "price": 197,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80",

    },
    "cheese-ranch-pasta": {
      "name": "Cheese Ranch Pasta",
      "nameAr": "Cheese Ranch Pasta",
      "description": "",
      "descriptionAr": "",
      "price": 238,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",

    },
    "mammo-pasta": {
      "name": "Mammo Pasta",
      "nameAr": "Mammo Pasta",
      "description": "",
      "descriptionAr": "",
      "price": 196,
      "category": "food",
      "available": true,
      "image": "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80",

    }
  },
  "sandwiches": {
    "crispy-chicken": {
      "name": "Crispy Chicken",
      "nameAr": "Crispy Chicken",
      "description": "",
      "descriptionAr": "",
      "price": 187,
      "category": "sandwiches",
      "available": true,
      "image": "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&q=80",

    },
    "chicken-ranch": {
      "name": "Chicken Ranch",
      "nameAr": "Chicken Ranch",
      "description": "",
      "descriptionAr": "",
      "price": 206,
      "category": "sandwiches",
      "available": true,
      "image": "https://images.unsplash.com/photo-1485423035951-3e36986808e0?w=400&q=80",

    },
    "mexicans": {
      "name": "Mexicans",
      "nameAr": "Mexicans",
      "description": "",
      "descriptionAr": "",
      "price": 219,
      "category": "sandwiches",
      "available": true,
      "image": "https://images.unsplash.com/photo-1485423035951-3e36986808e0?w=400&q=80",

    },
    "fillet-cheese-steak": {
      "name": "Fillet Cheese Steak",
      "nameAr": "Fillet Cheese Steak",
      "description": "",
      "descriptionAr": "",
      "price": 256,
      "category": "sandwiches",
      "available": true,
      "image": "https://images.unsplash.com/photo-1524350876685-274059332603?w=400&q=80",

    },
    "chicken-bacon": {
      "name": "Chicken Bacon",
      "nameAr": "Chicken Bacon",
      "description": "",
      "descriptionAr": "",
      "price": 234,
      "category": "sandwiches",
      "available": true,
      "image": "https://images.unsplash.com/photo-1485423035951-3e36986808e0?w=400&q=80",

    },
    "grilled-chicken": {
      "name": "Grilled Chicken",
      "nameAr": "Grilled Chicken",
      "description": "",
      "descriptionAr": "",
      "price": 207,
      "category": "sandwiches",
      "available": true,
      "image": "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&q=80",

    },
    "chicken-fajita": {
      "name": "Chicken Fajita",
      "nameAr": "Chicken Fajita",
      "description": "",
      "descriptionAr": "",
      "price": 226,
      "category": "sandwiches",
      "available": true,
      "image": "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&q=80",

    },
    "chicken-pepperoni": {
      "name": "Chicken Pepperoni",
      "nameAr": "Chicken Pepperoni",
      "description": "",
      "descriptionAr": "",
      "price": 234,
      "category": "sandwiches",
      "available": true,
      "image": "https://images.unsplash.com/photo-1485423035951-3e36986808e0?w=400&q=80",

    },
    "beef-fajitas": {
      "name": "Beef Fajitas",
      "nameAr": "Beef Fajitas",
      "description": "",
      "descriptionAr": "",
      "price": 236,
      "category": "sandwiches",
      "available": true,
      "image": "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&q=80",

    },
    "cordon-bleu": {
      "name": "Cordon Bleu",
      "nameAr": "Cordon Bleu",
      "description": "",
      "descriptionAr": "",
      "price": 201,
      "category": "sandwiches",
      "available": true,
      "image": "https://images.unsplash.com/photo-1524350876685-274059332603?w=400&q=80",

    }
  },
  "mains": {
    "chicken-grill": {
      "name": "Chicken Grill",
      "nameAr": "Chicken Grill",
      "description": "",
      "descriptionAr": "",
      "price": 334,
      "category": "mains",
      "available": true,
      "image": "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=400&q=80",

    },
    "chicken-lemon": {
      "name": "Chicken Lemon",
      "nameAr": "Chicken Lemon",
      "description": "",
      "descriptionAr": "",
      "price": 341,
      "category": "mains",
      "available": true,
      "image": "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=400&q=80",

    },
    "cordon-bleu": {
      "name": "Cordon Bleu",
      "nameAr": "Cordon Bleu",
      "description": "",
      "descriptionAr": "",
      "price": 357,
      "category": "mains",
      "available": true,
      "image": "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&q=80",

    },
    "country-fried-chicken": {
      "name": "Country Fried Chicken",
      "nameAr": "Country Fried Chicken",
      "description": "",
      "descriptionAr": "",
      "price": 363,
      "category": "mains",
      "available": true,
      "image": "https://images.unsplash.com/photo-1544025162-d76694265947?w=400&q=80",

    },
    "chicken-pesto": {
      "name": "Chicken Pesto",
      "nameAr": "Chicken Pesto",
      "description": "",
      "descriptionAr": "",
      "price": 347,
      "category": "mains",
      "available": true,
      "image": "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&q=80",

    },
    "chicken-fromage": {
      "name": "Chicken Fromage",
      "nameAr": "Chicken Fromage",
      "description": "",
      "descriptionAr": "",
      "price": 368,
      "category": "mains",
      "available": true,
      "image": "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&q=80",

    },
    "chicken-gravy": {
      "name": "Chicken Gravy",
      "nameAr": "Chicken Gravy",
      "description": "",
      "descriptionAr": "",
      "price": 374,
      "category": "mains",
      "available": true,
      "image": "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&q=80",

    },
    "fajita": {
      "name": "Fajita",
      "nameAr": "Fajita",
      "description": "",
      "descriptionAr": "",
      "price": 335,
      "category": "mains",
      "available": true,
      "image": "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=400&q=80",

    },
    "grilled-fillet": {
      "name": "Grilled Fillet",
      "nameAr": "Grilled Fillet",
      "description": "",
      "descriptionAr": "",
      "price": 426,
      "category": "mains",
      "available": true,
      "image": "https://images.unsplash.com/photo-1544025162-d76694265947?w=400&q=80",

    },
    "beef-stroganoff": {
      "name": "Beef Stroganoff",
      "nameAr": "Beef Stroganoff",
      "description": "",
      "descriptionAr": "",
      "price": 439,
      "category": "mains",
      "available": true,
      "image": "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=400&q=80",

    },
    "beef-fajitas": {
      "name": "Beef Fajitas",
      "nameAr": "Beef Fajitas",
      "description": "",
      "descriptionAr": "",
      "price": 429,
      "category": "mains",
      "available": true,
      "image": "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&q=80",

    }
  },
  "burgers": {
    "classic-burger": {
      "name": "Classic Burger",
      "nameAr": "Classic Burger",
      "description": "",
      "descriptionAr": "",
      "price": 228,
      "category": "burgers",
      "available": true,
      "image": "https://images.unsplash.com/photo-1586190848861-99aa4a171f90?w=400&q=80",

    },
    "cheese-burger": {
      "name": "Cheese Burger",
      "nameAr": "Cheese Burger",
      "description": "",
      "descriptionAr": "",
      "price": 238,
      "category": "burgers",
      "available": true,
      "image": "https://images.unsplash.com/photo-1553979459-d5f9a8a9a9a8?w=400&q=80",

    },
    "smoke-burger": {
      "name": "Smoke Burger",
      "nameAr": "Smoke Burger",
      "description": "",
      "descriptionAr": "",
      "price": 264,
      "category": "burgers",
      "available": true,
      "image": "https://images.unsplash.com/photo-1586190848861-99aa4a171f90?w=400&q=80",

    },
    "fire-burger": {
      "name": "Fire Burger",
      "nameAr": "Fire Burger",
      "description": "",
      "descriptionAr": "",
      "price": 237,
      "category": "burgers",
      "available": true,
      "image": "https://images.unsplash.com/photo-1553979459-d5f9a8a9a9a8?w=400&q=80",

    },
    "bbq-burger": {
      "name": "BBQ Burger",
      "nameAr": "BBQ Burger",
      "description": "",
      "descriptionAr": "",
      "price": 244,
      "category": "burgers",
      "available": true,
      "image": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",

    },
    "texas-burger": {
      "name": "Texas Burger",
      "nameAr": "Texas Burger",
      "description": "",
      "descriptionAr": "",
      "price": 273,
      "category": "burgers",
      "available": true,
      "image": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",

    },
    "classic-smash": {
      "name": "Classic Smash",
      "nameAr": "Classic Smash",
      "description": "",
      "descriptionAr": "",
      "price": 227,
      "category": "burgers",
      "available": true,
      "image": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",

    },
    "smoke-smash-burger": {
      "name": "Smoke Smash Burger",
      "nameAr": "Smoke Smash Burger",
      "description": "",
      "descriptionAr": "",
      "price": 282,
      "category": "burgers",
      "available": true,
      "image": "https://images.unsplash.com/photo-1586190848861-99aa4a171f90?w=400&q=80",

    },
    "smash-mushroom-boom": {
      "name": "Smash Mushroom Boom",
      "nameAr": "Smash Mushroom Boom",
      "description": "",
      "descriptionAr": "",
      "price": 252,
      "category": "burgers",
      "available": true,
      "image": "https://images.unsplash.com/photo-1586190848861-99aa4a171f90?w=400&q=80",

    },
    "fried-club": {
      "name": "Fried Club",
      "nameAr": "Fried Club",
      "description": "",
      "descriptionAr": "",
      "price": 281,
      "category": "burgers",
      "available": true,
      "image": "https://images.unsplash.com/photo-1553979459-d5f9a8a9a9a8?w=400&q=80",

    },
    "fire-smash-burger": {
      "name": "Fire Smash Burger",
      "nameAr": "Fire Smash Burger",
      "description": "",
      "descriptionAr": "",
      "price": 257,
      "category": "burgers",
      "available": true,
      "image": "https://images.unsplash.com/photo-1586190848861-99aa4a171f90?w=400&q=80",

    },
    "chili-ranch": {
      "name": "Chili Ranch",
      "nameAr": "Chili Ranch",
      "description": "",
      "descriptionAr": "",
      "price": 267,
      "category": "burgers",
      "available": true,
      "image": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",

    },
    "oven-baked-smash": {
      "name": "Oven Baked Smash",
      "nameAr": "Oven Baked Smash",
      "description": "",
      "descriptionAr": "",
      "price": 279,
      "category": "burgers",
      "available": true,
      "image": "https://images.unsplash.com/photo-1586190848861-99aa4a171f90?w=400&q=80",

    },
    "classic-fried-chicken": {
      "name": "Classic Fried Chicken",
      "nameAr": "Classic Fried Chicken",
      "description": "",
      "descriptionAr": "",
      "price": 216,
      "category": "burgers",
      "available": true,
      "image": "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&q=80",

    },
    "fire-fried-chicken": {
      "name": "Fire Fried Chicken",
      "nameAr": "Fire Fried Chicken",
      "description": "",
      "descriptionAr": "",
      "price": 221,
      "category": "burgers",
      "available": true,
      "image": "https://images.unsplash.com/photo-1586190848861-99aa4a171f90?w=400&q=80",

    },
    "smoke-fried-chicken": {
      "name": "Smoke Fried Chicken",
      "nameAr": "Smoke Fried Chicken",
      "description": "",
      "descriptionAr": "",
      "price": 249,
      "category": "burgers",
      "available": true,
      "image": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",

    },
    "fried-festival": {
      "name": "Fried Festival",
      "nameAr": "Fried Festival",
      "description": "",
      "descriptionAr": "",
      "price": 265,
      "category": "burgers",
      "available": true,
      "image": "https://images.unsplash.com/photo-1553979459-d5f9a8a9a9a8?w=400&q=80",

    }
  },
  "extras": {
    "extra-chicken": {
      "name": "Extra Chicken",
      "nameAr": "Extra Chicken",
      "description": "",
      "descriptionAr": "",
      "price": 50,
      "category": "extras",
      "available": true,
      "image": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",

    },
    "extra-cheese": {
      "name": "Extra Cheese",
      "nameAr": "Extra Cheese",
      "description": "",
      "descriptionAr": "",
      "price": 35,
      "category": "extras",
      "available": true,
      "image": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",

    },
    "extra-bread": {
      "name": "Extra Bread",
      "nameAr": "Extra Bread",
      "description": "",
      "descriptionAr": "",
      "price": 25,
      "category": "extras",
      "available": true,
      "image": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",

    },
    "extra-meat": {
      "name": "Extra Meat",
      "nameAr": "Extra Meat",
      "description": "",
      "descriptionAr": "",
      "price": 70,
      "category": "extras",
      "available": true,
      "image": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",

    },
    "extra-fries": {
      "name": "Extra Fries",
      "nameAr": "Extra Fries",
      "description": "",
      "descriptionAr": "",
      "price": 60,
      "category": "extras",
      "available": true,
      "image": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",

    },
    "extra-rice": {
      "name": "Extra Rice",
      "nameAr": "Extra Rice",
      "description": "",
      "descriptionAr": "",
      "price": 45,
      "category": "extras",
      "available": true,
      "image": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",

    },
    "extra-mushroom": {
      "name": "Extra Mushroom",
      "nameAr": "Extra Mushroom",
      "description": "",
      "descriptionAr": "",
      "price": 40,
      "category": "extras",
      "available": true,
      "image": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",

    },
    "extra-sauce": {
      "name": "Extra Sauce",
      "nameAr": "Extra Sauce",
      "description": "",
      "descriptionAr": "",
      "price": 35,
      "category": "extras",
      "available": true,
      "image": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",

    },
    "sweet-chili": {
      "name": "Sweet Chili",
      "nameAr": "Sweet Chili",
      "description": "",
      "descriptionAr": "",
      "price": 25,
      "category": "extras",
      "available": true,
      "image": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",

    },
    "jalapeno": {
      "name": "Jalapeno",
      "nameAr": "Jalapeno",
      "description": "",
      "descriptionAr": "",
      "price": 20,
      "category": "extras",
      "available": true,
      "image": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",

    },
    "sauce": {
      "name": "Sauce",
      "nameAr": "Sauce",
      "description": "",
      "descriptionAr": "",
      "price": 25,
      "category": "extras",
      "available": true,
      "image": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",

    },
    "flavor": {
      "name": "Flavor",
      "nameAr": "Flavor",
      "description": "",
      "descriptionAr": "",
      "price": 25,
      "category": "extras",
      "available": true,
      "image": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",

    },
    "topping": {
      "name": "Topping",
      "nameAr": "Topping",
      "description": "",
      "descriptionAr": "",
      "price": 30,
      "category": "extras",
      "available": true,
      "image": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",

    },
    "milk": {
      "name": "Milk",
      "nameAr": "Milk",
      "description": "",
      "descriptionAr": "",
      "price": 25,
      "category": "extras",
      "available": true,
      "image": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",

    },
    "ice-cream": {
      "name": "Ice Cream",
      "nameAr": "Ice Cream",
      "description": "",
      "descriptionAr": "",
      "price": 50,
      "category": "extras",
      "available": true,
      "image": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",

    },
    "nuts": {
      "name": "Nuts",
      "nameAr": "Nuts",
      "description": "",
      "descriptionAr": "",
      "price": 45,
      "category": "extras",
      "available": true,
      "image": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",

    },
    "pistachio": {
      "name": "Pistachio",
      "nameAr": "Pistachio",
      "description": "",
      "descriptionAr": "",
      "price": 50,
      "category": "extras",
      "available": true,
      "image": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",

    },
    "espresso": {
      "name": "Espresso",
      "nameAr": "Espresso",
      "description": "",
      "descriptionAr": "",
      "price": 35,
      "category": "extras",
      "available": true,
      "image": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400&q=80",

    }
  },
  "hot_drinks": {
    "tea": {
      "name": "Tea",
      "nameAr": "Tea",
      "description": "",
      "descriptionAr": "",
      "price": 55,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80",

    },
    "flavor-tea": {
      "name": "Flavor Tea",
      "nameAr": "Flavor Tea",
      "description": "",
      "descriptionAr": "",
      "price": 65,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=400&q=80",

    },
    "zarda-tea": {
      "name": "Zarda Tea",
      "nameAr": "Zarda Tea",
      "description": "",
      "descriptionAr": "",
      "price": 60,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=400&q=80",

    },
    "herbs": {
      "name": "Herbs",
      "nameAr": "Herbs",
      "description": "",
      "descriptionAr": "",
      "price": 65,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&q=80",

    },
    "mixed-herbs": {
      "name": "Mixed Herbs",
      "nameAr": "Mixed Herbs",
      "description": "",
      "descriptionAr": "",
      "price": 95,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1534778101976-62847782c213?w=400&q=80",

    },
    "single-turkish-coffee": {
      "name": "Single Turkish Coffee",
      "nameAr": "Single Turkish Coffee",
      "description": "",
      "descriptionAr": "",
      "price": 55,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=400&q=80",

    },
    "double-turkish-coffee": {
      "name": "Double Turkish Coffee",
      "nameAr": "Double Turkish Coffee",
      "description": "",
      "descriptionAr": "",
      "price": 70,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&q=80",

    },
    "french-coffee": {
      "name": "French Coffee",
      "nameAr": "French Coffee",
      "description": "",
      "descriptionAr": "",
      "price": 80,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80",

    },
    "hazelnut-coffee": {
      "name": "Hazelnut Coffee",
      "nameAr": "Hazelnut Coffee",
      "description": "",
      "descriptionAr": "",
      "price": 85,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1534778101976-62847782c213?w=400&q=80",

    },
    "nutella-coffee": {
      "name": "Nutella Coffee",
      "nameAr": "Nutella Coffee",
      "description": "",
      "descriptionAr": "",
      "price": 95,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80",

    },
    "hot-cidier": {
      "name": "Hot Cidier",
      "nameAr": "Hot Cidier",
      "description": "",
      "descriptionAr": "",
      "price": 85,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&q=80",

    },
    "single-espresso": {
      "name": "Single Espresso",
      "nameAr": "Single Espresso",
      "description": "",
      "descriptionAr": "",
      "price": 58,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1534778101976-62847782c213?w=400&q=80",

    },
    "double-espresso": {
      "name": "Double Espresso",
      "nameAr": "Double Espresso",
      "description": "",
      "descriptionAr": "",
      "price": 80,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&q=80",

    },
    "single-macchiato": {
      "name": "Single Macchiato",
      "nameAr": "Single Macchiato",
      "description": "",
      "descriptionAr": "",
      "price": 65,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=400&q=80",

    },
    "espresso-con-panna": {
      "name": "Espresso Con Panna",
      "nameAr": "Espresso Con Panna",
      "description": "",
      "descriptionAr": "",
      "price": 78,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80",

    },
    "espresso-avocado": {
      "name": "Espresso Avocado",
      "nameAr": "Espresso Avocado",
      "description": "",
      "descriptionAr": "",
      "price": 84,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80",

    },
    "bon-bon-coffee": {
      "name": "Bon Bon Coffee",
      "nameAr": "Bon Bon Coffee",
      "description": "",
      "descriptionAr": "",
      "price": 85,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1534778101976-62847782c213?w=400&q=80",

    },
    "americano-(white-black)": {
      "name": "Americano (white-black)",
      "nameAr": "Americano (white-black)",
      "description": "",
      "descriptionAr": "",
      "price": 91,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&q=80",
    },
    "cappuccino": {
      "name": "Cappuccino",
      "nameAr": "Cappuccino",
      "description": "",
      "descriptionAr": "",
      "price": 104,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1534778101976-62847782c213?w=400&q=80",

    },
    "latte": {
      "name": "Latte",
      "nameAr": "Latte",
      "description": "",
      "descriptionAr": "",
      "price": 88,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80",

    },
    "flat-white": {
      "name": "Flat White",
      "nameAr": "Flat White",
      "description": "",
      "descriptionAr": "",
      "price": 110,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=400&q=80",

    },
    "caramel-macchiato": {
      "name": "Caramel Macchiato",
      "nameAr": "Caramel Macchiato",
      "description": "",
      "descriptionAr": "",
      "price": 105,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&q=80",

    },
    "mocha": {
      "name": "Mocha",
      "nameAr": "Mocha",
      "description": "",
      "descriptionAr": "",
      "price": 105,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80",

    },
    "hazelnut-mocha-(nutella)": {
      "name": "Hazelnut Mocha (Nutella)",
      "nameAr": "Hazelnut Mocha (Nutella)",
      "description": "",
      "descriptionAr": "",
      "price": 110,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80",
    },
    "mocha-mint": {
      "name": "Mocha Mint",
      "nameAr": "Mocha Mint",
      "description": "",
      "descriptionAr": "",
      "price": 107,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&q=80",

    },
    "lotus-latte": {
      "name": "Lotus Latte",
      "nameAr": "Lotus Latte",
      "description": "",
      "descriptionAr": "",
      "price": 125,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&q=80",

    },
    "spanish-latte": {
      "name": "Spanish Latte",
      "nameAr": "Spanish Latte",
      "description": "",
      "descriptionAr": "",
      "price": 115,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=400&q=80",

    },
    "hazelnut-spanish-latte": {
      "name": "Hazelnut Spanish Latte",
      "nameAr": "Hazelnut Spanish Latte",
      "description": "",
      "descriptionAr": "",
      "price": 135,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&q=80",

    },
    "mocha-marshmallow": {
      "name": "Mocha Marshmallow",
      "nameAr": "Mocha Marshmallow",
      "description": "",
      "descriptionAr": "",
      "price": 125,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1534778101976-62847782c213?w=400&q=80",

    },
    "hazelnut-caramel": {
      "name": "Hazelnut Caramel",
      "nameAr": "Hazelnut Caramel",
      "description": "",
      "descriptionAr": "",
      "price": 108,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&q=80",

    },
    "nescafe": {
      "name": "Nescafe",
      "nameAr": "Nescafe",
      "description": "",
      "descriptionAr": "",
      "price": 80,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&q=80",

    },
    "classic-corto": {
      "name": "Classic Corto",
      "nameAr": "Classic Corto",
      "description": "",
      "descriptionAr": "",
      "price": 97,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=400&q=80",

    },
    "mocha-corto": {
      "name": "Mocha Corto",
      "nameAr": "Mocha Corto",
      "description": "",
      "descriptionAr": "",
      "price": 119,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&q=80",

    },
    "corto-caramel": {
      "name": "Corto Caramel",
      "nameAr": "Corto Caramel",
      "description": "",
      "descriptionAr": "",
      "price": 119,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&q=80",

    },
    "black-corto": {
      "name": "Black Corto",
      "nameAr": "Black Corto",
      "description": "",
      "descriptionAr": "",
      "price": 114,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80",

    },
    "classic-hot-chocolate": {
      "name": "Classic Hot Chocolate",
      "nameAr": "Classic Hot Chocolate",
      "description": "",
      "descriptionAr": "",
      "price": 144,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&q=80",

    },
    "milk-hot-chocolate": {
      "name": "Milk Hot Chocolate",
      "nameAr": "Milk Hot Chocolate",
      "description": "",
      "descriptionAr": "",
      "price": 169,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&q=80",

    },
    "dark-hot-chocolate": {
      "name": "Dark Hot Chocolate",
      "nameAr": "Dark Hot Chocolate",
      "description": "",
      "descriptionAr": "",
      "price": 169,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&q=80",

    },
    "hot-lotus": {
      "name": "Hot Lotus",
      "nameAr": "Hot Lotus",
      "description": "",
      "descriptionAr": "",
      "price": 169,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&q=80",

    },
    "hot-pistachio": {
      "name": "Hot Pistachio",
      "nameAr": "Hot Pistachio",
      "description": "",
      "descriptionAr": "",
      "price": 179,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=400&q=80",

    },
    "hot-chocolate-marshmallow": {
      "name": "Hot Chocolate Marshmallow",
      "nameAr": "Hot Chocolate Marshmallow",
      "description": "",
      "descriptionAr": "",
      "price": 169,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80",

    },
    "oreo-hot-chocolate": {
      "name": "Oreo Hot Chocolate",
      "nameAr": "Oreo Hot Chocolate",
      "description": "",
      "descriptionAr": "",
      "price": 169,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&q=80",

    },
    "cinnamon-hot-chocolate": {
      "name": "Cinnamon Hot Chocolate",
      "nameAr": "Cinnamon Hot Chocolate",
      "description": "",
      "descriptionAr": "",
      "price": 169,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=400&q=80",

    },
    "classic-sahlab-(nuts)": {
      "name": "Classic Sahlab (Nuts)",
      "nameAr": "Classic Sahlab (Nuts)",
      "description": "",
      "descriptionAr": "",
      "price": 104,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80",
    },
    "nutella-sahlab": {
      "name": "Nutella Sahlab",
      "nameAr": "Nutella Sahlab",
      "description": "",
      "descriptionAr": "",
      "price": 139,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&q=80",

    },
    "lotus-sahlab": {
      "name": "Lotus Sahlab",
      "nameAr": "Lotus Sahlab",
      "description": "",
      "descriptionAr": "",
      "price": 149,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&q=80",

    },
    "pistachio-sahlab": {
      "name": "Pistachio Sahlab",
      "nameAr": "Pistachio Sahlab",
      "description": "",
      "descriptionAr": "",
      "price": 169,
      "category": "hot_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&q=80",

    }
  },
  "cold_drinks": {
    "frappuccino": {
      "name": "Frappuccino",
      "nameAr": "Frappuccino",
      "description": "",
      "descriptionAr": "",
      "price": 143,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1543429258-c5ca3f4c9c8e?w=400&q=80",

    },
    "frappe-strong": {
      "name": "Frappe Strong",
      "nameAr": "Frappe Strong",
      "description": "",
      "descriptionAr": "",
      "price": 159,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1497534446932-c4f89e60f298?w=400&q=80",

    },
    "caramel-macchiato-frappe": {
      "name": "Caramel Macchiato Frappe",
      "nameAr": "Caramel Macchiato Frappe",
      "description": "",
      "descriptionAr": "",
      "price": 169,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",

    },
    "mocha-frappe": {
      "name": "Mocha Frappe",
      "nameAr": "Mocha Frappe",
      "description": "",
      "descriptionAr": "",
      "price": 174,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1543429258-c5ca3f4c9c8e?w=400&q=80",

    },
    "mocha-marshmallow-frappe": {
      "name": "Mocha Marshmallow Frappe",
      "nameAr": "Mocha Marshmallow Frappe",
      "description": "",
      "descriptionAr": "",
      "price": 194,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1497534446932-c4f89e60f298?w=400&q=80",

    },
    "white-mocha-frappe": {
      "name": "White Mocha Frappe",
      "nameAr": "White Mocha Frappe",
      "description": "",
      "descriptionAr": "",
      "price": 174,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1543429258-c5ca3f4c9c8e?w=400&q=80",

    },
    "oreo-frappe": {
      "name": "Oreo Frappe",
      "nameAr": "Oreo Frappe",
      "description": "",
      "descriptionAr": "",
      "price": 164,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1497534446932-c4f89e60f298?w=400&q=80",

    },
    "lotus-frappe": {
      "name": "Lotus Frappe",
      "nameAr": "Lotus Frappe",
      "description": "",
      "descriptionAr": "",
      "price": 195,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",

    },
    "blueberry-vanilla-frappe": {
      "name": "Blueberry Vanilla Frappe",
      "nameAr": "Blueberry Vanilla Frappe",
      "description": "",
      "descriptionAr": "",
      "price": 159,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",

    },
    "strawberry-vanilla-frappe": {
      "name": "Strawberry Vanilla Frappe",
      "nameAr": "Strawberry Vanilla Frappe",
      "description": "",
      "descriptionAr": "",
      "price": 159,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",

    },
    "chocolate-frappe": {
      "name": "Chocolate Frappe",
      "nameAr": "Chocolate Frappe",
      "description": "",
      "descriptionAr": "",
      "price": 164,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",

    },
    "hazelnut-frappe": {
      "name": "Hazelnut Frappe",
      "nameAr": "Hazelnut Frappe",
      "description": "",
      "descriptionAr": "",
      "price": 149,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",

    },
    "espresso-energy": {
      "name": "Espresso Energy",
      "nameAr": "Espresso Energy",
      "description": "",
      "descriptionAr": "",
      "price": 199,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",

    },
    "iced-latte": {
      "name": "Iced Latte",
      "nameAr": "Iced Latte",
      "description": "",
      "descriptionAr": "",
      "price": 139,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1543429258-c5ca3f4c9c8e?w=400&q=80",

    },
    "iced-cappuccino": {
      "name": "Iced Cappuccino",
      "nameAr": "Iced Cappuccino",
      "description": "",
      "descriptionAr": "",
      "price": 154,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1497534446932-c4f89e60f298?w=400&q=80",

    },
    "iced-nescafe": {
      "name": "Iced Nescafe",
      "nameAr": "Iced Nescafe",
      "description": "",
      "descriptionAr": "",
      "price": 139,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1497534446932-c4f89e60f298?w=400&q=80",

    },
    "iced-mocha": {
      "name": "Iced Mocha",
      "nameAr": "Iced Mocha",
      "description": "",
      "descriptionAr": "",
      "price": 149,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1543429258-c5ca3f4c9c8e?w=400&q=80",

    },
    "iced-white-mocha": {
      "name": "Iced White Mocha",
      "nameAr": "Iced White Mocha",
      "description": "",
      "descriptionAr": "",
      "price": 149,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1543429258-c5ca3f4c9c8e?w=400&q=80",

    },
    "iced-caramel-macchiato": {
      "name": "Iced Caramel Macchiato",
      "nameAr": "Iced Caramel Macchiato",
      "description": "",
      "descriptionAr": "",
      "price": 154,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80",

    },
    "iced-spanish-latte": {
      "name": "Iced Spanish Latte",
      "nameAr": "Iced Spanish Latte",
      "description": "",
      "descriptionAr": "",
      "price": 179,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",

    },
    "ice-spanish-hazelnut-latte": {
      "name": "Ice Spanish Hazelnut Latte",
      "nameAr": "Ice Spanish Hazelnut Latte",
      "description": "",
      "descriptionAr": "",
      "price": 189,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1497534446932-c4f89e60f298?w=400&q=80",

    },
    "iced-rose-latte": {
      "name": "Iced Rose Latte",
      "nameAr": "Iced Rose Latte",
      "description": "",
      "descriptionAr": "",
      "price": 174,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",

    },
    "blue-coffee-ice": {
      "name": "Blue Coffee Ice",
      "nameAr": "Blue Coffee Ice",
      "description": "",
      "descriptionAr": "",
      "price": 174,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80",

    },
    "ice-boba-coffee": {
      "name": "Ice Boba Coffee",
      "nameAr": "Ice Boba Coffee",
      "description": "",
      "descriptionAr": "",
      "price": 184,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1543429258-c5ca3f4c9c8e?w=400&q=80",

    },
    "ice-tea-black": {
      "name": "Ice Tea Black",
      "nameAr": "Ice Tea Black",
      "description": "",
      "descriptionAr": "",
      "price": 89,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1497534446932-c4f89e60f298?w=400&q=80",

    },
    "ice-tea-green": {
      "name": "Ice Tea Green",
      "nameAr": "Ice Tea Green",
      "description": "",
      "descriptionAr": "",
      "price": 104,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",

    },
    "ice-tea-peach": {
      "name": "Ice Tea Peach",
      "nameAr": "Ice Tea Peach",
      "description": "",
      "descriptionAr": "",
      "price": 124,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",

    },
    "ice-tea-lemon-honey": {
      "name": "Ice Tea Lemon Honey",
      "nameAr": "Ice Tea Lemon Honey",
      "description": "",
      "descriptionAr": "",
      "price": 134,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1543429258-c5ca3f4c9c8e?w=400&q=80",

    },
    "ice-tea-raspberry": {
      "name": "Ice Tea Raspberry",
      "nameAr": "Ice Tea Raspberry",
      "description": "",
      "descriptionAr": "",
      "price": 124,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80",

    },
    "lemon-mint": {
      "name": "Lemon Mint",
      "nameAr": "Lemon Mint",
      "description": "",
      "descriptionAr": "",
      "price": 99,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80",

    },
    "lemon-pink": {
      "name": "Lemon Pink",
      "nameAr": "Lemon Pink",
      "description": "",
      "descriptionAr": "",
      "price": 99,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",

    },
    "lemon-strawberry": {
      "name": "Lemon Strawberry",
      "nameAr": "Lemon Strawberry",
      "description": "",
      "descriptionAr": "",
      "price": 99,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1543429258-c5ca3f4c9c8e?w=400&q=80",

    },
    "lemon-passion": {
      "name": "Lemon Passion",
      "nameAr": "Lemon Passion",
      "description": "",
      "descriptionAr": "",
      "price": 109,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",

    },
    "classic-mojito": {
      "name": "Classic Mojito",
      "nameAr": "Classic Mojito",
      "description": "",
      "descriptionAr": "",
      "price": 129,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1543429258-c5ca3f4c9c8e?w=400&q=80",

    },
    "blueberry-mojito": {
      "name": "Blueberry Mojito",
      "nameAr": "Blueberry Mojito",
      "description": "",
      "descriptionAr": "",
      "price": 184,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80",

    },
    "mixed-berry-mojito": {
      "name": "Mixed Berry Mojito",
      "nameAr": "Mixed Berry Mojito",
      "description": "",
      "descriptionAr": "",
      "price": 181,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80",

    },
    "passion-mojito": {
      "name": "Passion Mojito",
      "nameAr": "Passion Mojito",
      "description": "",
      "descriptionAr": "",
      "price": 179,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80",

    },
    "strawberry-mojito": {
      "name": "Strawberry Mojito",
      "nameAr": "Strawberry Mojito",
      "description": "",
      "descriptionAr": "",
      "price": 188,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1543429258-c5ca3f4c9c8e?w=400&q=80",

    },
    "peach-mojito": {
      "name": "Peach Mojito",
      "nameAr": "Peach Mojito",
      "description": "",
      "descriptionAr": "",
      "price": 189,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",

    },
    "apple-mojito": {
      "name": "Apple Mojito",
      "nameAr": "Apple Mojito",
      "description": "",
      "descriptionAr": "",
      "price": 184,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1543429258-c5ca3f4c9c8e?w=400&q=80",

    },
    "pineapple-mojito": {
      "name": "Pineapple Mojito",
      "nameAr": "Pineapple Mojito",
      "description": "",
      "descriptionAr": "",
      "price": 197,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",

    },
    "red-bull-mojito": {
      "name": "Red Bull Mojito",
      "nameAr": "Red Bull Mojito",
      "description": "",
      "descriptionAr": "",
      "price": 204,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",

    },
    "passion-blue": {
      "name": "Passion Blue",
      "nameAr": "Passion Blue",
      "description": "",
      "descriptionAr": "",
      "price": 169,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1543429258-c5ca3f4c9c8e?w=400&q=80",

    },
    "red-bull-berry": {
      "name": "Red Bull Berry",
      "nameAr": "Red Bull Berry",
      "description": "",
      "descriptionAr": "",
      "price": 209,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1543429258-c5ca3f4c9c8e?w=400&q=80",

    },
    "red-bull-blue": {
      "name": "Red Bull Blue",
      "nameAr": "Red Bull Blue",
      "description": "",
      "descriptionAr": "",
      "price": 204,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1543429258-c5ca3f4c9c8e?w=400&q=80",

    },
    "cherry-cola": {
      "name": "Cherry Cola",
      "nameAr": "Cherry Cola",
      "description": "",
      "descriptionAr": "",
      "price": 139,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",

    },
    "french-cola": {
      "name": "French Cola",
      "nameAr": "French Cola",
      "description": "",
      "descriptionAr": "",
      "price": 144,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1497534446932-c4f89e60f298?w=400&q=80",

    },
    "boba-mojito-(blueberry,-passion,-strawberry,-green-apple)": {
      "name": "Boba Mojito (Blueberry, Passion, Strawberry, Green Apple)",
      "nameAr": "Boba Mojito (Blueberry, Passion, Strawberry, Green Apple)",
      "description": "",
      "descriptionAr": "",
      "price": 224,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80",
    },
    "boba-tea-blueberry": {
      "name": "Boba Tea Blueberry",
      "nameAr": "Boba Tea Blueberry",
      "description": "",
      "descriptionAr": "",
      "price": 159,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80",

    },
    "boba-tea-passion-fruit": {
      "name": "Boba Tea Passion Fruit",
      "nameAr": "Boba Tea Passion Fruit",
      "description": "",
      "descriptionAr": "",
      "price": 164,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",

    },
    "boba-tea-strawberry": {
      "name": "Boba Tea Strawberry",
      "nameAr": "Boba Tea Strawberry",
      "description": "",
      "descriptionAr": "",
      "price": 169,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1497534446932-c4f89e60f298?w=400&q=80",

    },
    "boba-tea-green-apple": {
      "name": "Boba Tea Green Apple",
      "nameAr": "Boba Tea Green Apple",
      "description": "",
      "descriptionAr": "",
      "price": 169,
      "category": "cold_drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1543429258-c5ca3f4c9c8e?w=400&q=80",

    }
  },
  "fresh": {
    "mango": {
      "name": "Mango",
      "nameAr": "Mango",
      "description": "",
      "descriptionAr": "",
      "price": 129,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&q=80",

    },
    "strawberry": {
      "name": "Strawberry",
      "nameAr": "Strawberry",
      "description": "",
      "descriptionAr": "",
      "price": 129,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1600271886742-f04cd1e0e5d2?w=400&q=80",

    },
    "guava": {
      "name": "Guava",
      "nameAr": "Guava",
      "description": "",
      "descriptionAr": "",
      "price": 133,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1621504455018-7d2e1e6a5f4e?w=400&q=80",

    },
    "orange": {
      "name": "Orange",
      "nameAr": "Orange",
      "description": "",
      "descriptionAr": "",
      "price": 121,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&q=80",

    },
    "watermelon": {
      "name": "Watermelon",
      "nameAr": "Watermelon",
      "description": "",
      "descriptionAr": "",
      "price": 149,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&q=80",

    },
    "kiwi": {
      "name": "Kiwi",
      "nameAr": "Kiwi",
      "description": "",
      "descriptionAr": "",
      "price": 160,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&q=80",

    },
    "dates": {
      "name": "Dates",
      "nameAr": "Dates",
      "description": "",
      "descriptionAr": "",
      "price": 130,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&q=80",

    },
    "pomegranate": {
      "name": "Pomegranate",
      "nameAr": "Pomegranate",
      "description": "",
      "descriptionAr": "",
      "price": 118,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1600271886742-f04cd1e0e5d2?w=400&q=80",

    },
    "banana": {
      "name": "Banana",
      "nameAr": "Banana",
      "description": "",
      "descriptionAr": "",
      "price": 129,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&q=80",

    },
    "lemon": {
      "name": "Lemon",
      "nameAr": "Lemon",
      "description": "",
      "descriptionAr": "",
      "price": 89,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1600271886742-f04cd1e0e5d2?w=400&q=80",

    },
    "lemon-mint": {
      "name": "Lemon Mint",
      "nameAr": "Lemon Mint",
      "description": "",
      "descriptionAr": "",
      "price": 104,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1621504455018-7d2e1e6a5f4e?w=400&q=80",

    },
    "pineapple": {
      "name": "Pineapple",
      "nameAr": "Pineapple",
      "description": "",
      "descriptionAr": "",
      "price": 139,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1600271886742-f04cd1e0e5d2?w=400&q=80",

    },
    "avocado": {
      "name": "Avocado",
      "nameAr": "Avocado",
      "description": "",
      "descriptionAr": "",
      "price": 168,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1600271886742-f04cd1e0e5d2?w=400&q=80",

    },
    "peach": {
      "name": "Peach",
      "nameAr": "Peach",
      "description": "",
      "descriptionAr": "",
      "price": 127,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1621504455018-7d2e1e6a5f4e?w=400&q=80",

    },
    "strawberry-banana": {
      "name": "Strawberry Banana",
      "nameAr": "Strawberry Banana",
      "description": "",
      "descriptionAr": "",
      "price": 137,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1621504455018-7d2e1e6a5f4e?w=400&q=80",

    },
    "mango-kiwi": {
      "name": "Mango Kiwi",
      "nameAr": "Mango Kiwi",
      "description": "",
      "descriptionAr": "",
      "price": 154,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1600271886742-f04cd1e0e5d2?w=400&q=80",

    },
    "copacabana": {
      "name": "Copacabana",
      "nameAr": "Copacabana",
      "description": "",
      "descriptionAr": "",
      "price": 129,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&q=80",

    },
    "white-mountain": {
      "name": "White Mountain",
      "nameAr": "White Mountain",
      "description": "",
      "descriptionAr": "",
      "price": 139,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&q=80",

    },
    "lemont-strawberry": {
      "name": "Lemont Strawberry",
      "nameAr": "Lemont Strawberry",
      "description": "",
      "descriptionAr": "",
      "price": 144,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1621504455018-7d2e1e6a5f4e?w=400&q=80",

    },
    "yellow-and-green": {
      "name": "Yellow and Green",
      "nameAr": "Yellow and Green",
      "description": "",
      "descriptionAr": "",
      "price": 149,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&q=80",

    },
    "pina-colada": {
      "name": "Pina Colada",
      "nameAr": "Pina Colada",
      "description": "",
      "descriptionAr": "",
      "price": 154,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1600271886742-f04cd1e0e5d2?w=400&q=80",

    },
    "blueberry": {
      "name": "Blueberry",
      "nameAr": "Blueberry",
      "description": "",
      "descriptionAr": "",
      "price": 139,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&q=80",

    },
    "mix-berry": {
      "name": "Mix Berry",
      "nameAr": "Mix Berry",
      "description": "",
      "descriptionAr": "",
      "price": 144,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&q=80",

    },
    "mango-peach": {
      "name": "Mango Peach",
      "nameAr": "Mango Peach",
      "description": "",
      "descriptionAr": "",
      "price": 154,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1600271886742-f04cd1e0e5d2?w=400&q=80",

    },
    "passion-fruit": {
      "name": "Passion Fruit",
      "nameAr": "Passion Fruit",
      "description": "",
      "descriptionAr": "",
      "price": 144,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1600271886742-f04cd1e0e5d2?w=400&q=80",

    },
    "passion-strawberry": {
      "name": "Passion Strawberry",
      "nameAr": "Passion Strawberry",
      "description": "",
      "descriptionAr": "",
      "price": 149,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&q=80",

    },
    "mango-passion": {
      "name": "Mango Passion",
      "nameAr": "Mango Passion",
      "description": "",
      "descriptionAr": "",
      "price": 134,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1621504455018-7d2e1e6a5f4e?w=400&q=80",

    },
    "blue-passion": {
      "name": "Blue Passion",
      "nameAr": "Blue Passion",
      "description": "",
      "descriptionAr": "",
      "price": 159,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1600271886742-f04cd1e0e5d2?w=400&q=80",

    },
    "strawberry-colada": {
      "name": "Strawberry Colada",
      "nameAr": "Strawberry Colada",
      "description": "",
      "descriptionAr": "",
      "price": 159,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1621504455018-7d2e1e6a5f4e?w=400&q=80",

    },
    "mango-colada": {
      "name": "Mango Colada",
      "nameAr": "Mango Colada",
      "description": "",
      "descriptionAr": "",
      "price": 159,
      "category": "fresh",
      "available": true,
      "image": "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&q=80",

    }
  },
  "milkshake": {
    "vanilla": {
      "name": "Vanilla",
      "nameAr": "Vanilla",
      "description": "",
      "descriptionAr": "",
      "price": 144,
      "category": "milkshake",
      "available": true,
      "image": "https://images.unsplash.com/photo-1572490122747-6938a5a5a7e4?w=400&q=80",

    },
    "chocolate": {
      "name": "Chocolate",
      "nameAr": "Chocolate",
      "description": "",
      "descriptionAr": "",
      "price": 149,
      "category": "milkshake",
      "available": true,
      "image": "https://images.unsplash.com/photo-1568901839119-631418a2910a?w=400&q=80",

    },
    "strawberry": {
      "name": "Strawberry",
      "nameAr": "Strawberry",
      "description": "",
      "descriptionAr": "",
      "price": 154,
      "category": "milkshake",
      "available": true,
      "image": "https://images.unsplash.com/photo-1568901839119-631418a2910a?w=400&q=80",

    },
    "mango": {
      "name": "Mango",
      "nameAr": "Mango",
      "description": "",
      "descriptionAr": "",
      "price": 154,
      "category": "milkshake",
      "available": true,
      "image": "https://images.unsplash.com/photo-1572490122747-6938a5a5a7e4?w=400&q=80",

    },
    "blueberry": {
      "name": "Blueberry",
      "nameAr": "Blueberry",
      "description": "",
      "descriptionAr": "",
      "price": 189,
      "category": "milkshake",
      "available": true,
      "image": "https://images.unsplash.com/photo-1572490122747-6938a5a5a7e4?w=400&q=80",

    },
    "mix-berry": {
      "name": "Mix Berry",
      "nameAr": "Mix Berry",
      "description": "",
      "descriptionAr": "",
      "price": 194,
      "category": "milkshake",
      "available": true,
      "image": "https://images.unsplash.com/photo-1572490122747-6938a5a5a7e4?w=400&q=80",

    },
    "toffee": {
      "name": "Toffee",
      "nameAr": "Toffee",
      "description": "",
      "descriptionAr": "",
      "price": 194,
      "category": "milkshake",
      "available": true,
      "image": "https://images.unsplash.com/photo-1579954115545-a04591eba6e5?w=400&q=80",

    },
    "oreo": {
      "name": "Oreo",
      "nameAr": "Oreo",
      "description": "",
      "descriptionAr": "",
      "price": 194,
      "category": "milkshake",
      "available": true,
      "image": "https://images.unsplash.com/photo-1568901839119-631418a2910a?w=400&q=80",

    },
    "nutella": {
      "name": "Nutella",
      "nameAr": "Nutella",
      "description": "",
      "descriptionAr": "",
      "price": 197,
      "category": "milkshake",
      "available": true,
      "image": "https://images.unsplash.com/photo-1572490122747-6938a5a5a7e4?w=400&q=80",

    },
    "strawberry-coconut": {
      "name": "Strawberry Coconut",
      "nameAr": "Strawberry Coconut",
      "description": "",
      "descriptionAr": "",
      "price": 184,
      "category": "milkshake",
      "available": true,
      "image": "https://images.unsplash.com/photo-1572490122747-6938a5a5a7e4?w=400&q=80",

    },
    "pistachio": {
      "name": "Pistachio",
      "nameAr": "Pistachio",
      "description": "",
      "descriptionAr": "",
      "price": 214,
      "category": "milkshake",
      "available": true,
      "image": "https://images.unsplash.com/photo-1579954115545-a04591eba6e5?w=400&q=80",

    },
    "kinder-bueno": {
      "name": "Kinder Bueno",
      "nameAr": "Kinder Bueno",
      "description": "",
      "descriptionAr": "",
      "price": 189,
      "category": "milkshake",
      "available": true,
      "image": "https://images.unsplash.com/photo-1572490122747-6938a5a5a7e4?w=400&q=80",

    },
    "coffee": {
      "name": "Coffee",
      "nameAr": "Coffee",
      "description": "",
      "descriptionAr": "",
      "price": 197,
      "category": "milkshake",
      "available": true,
      "image": "https://images.unsplash.com/photo-1568901839119-631418a2910a?w=400&q=80",

    },
    "lotus": {
      "name": "Lotus",
      "nameAr": "Lotus",
      "description": "",
      "descriptionAr": "",
      "price": 203,
      "category": "milkshake",
      "available": true,
      "image": "https://images.unsplash.com/photo-1579954115545-a04591eba6e5?w=400&q=80",

    },
    "passion-fruit": {
      "name": "Passion Fruit",
      "nameAr": "Passion Fruit",
      "description": "",
      "descriptionAr": "",
      "price": 174,
      "category": "milkshake",
      "available": true,
      "image": "https://images.unsplash.com/photo-1568901839119-631418a2910a?w=400&q=80",

    },
    "apples": {
      "name": "Apples",
      "nameAr": "Apples",
      "description": "",
      "descriptionAr": "",
      "price": 179,
      "category": "milkshake",
      "available": true,
      "image": "https://images.unsplash.com/photo-1568901839119-631418a2910a?w=400&q=80",

    }
  },
  "desserts": {
    "nutella": {
      "name": "Nutella",
      "nameAr": "Nutella",
      "description": "",
      "descriptionAr": "",
      "price": 184,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1563805042-7684c019a09d?w=400&q=80",

    },
    "mixed-chocolate": {
      "name": "Mixed Chocolate",
      "nameAr": "Mixed Chocolate",
      "description": "",
      "descriptionAr": "",
      "price": 234,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80",

    },
    "lotus-caramel": {
      "name": "Lotus Caramel",
      "nameAr": "Lotus Caramel",
      "description": "",
      "descriptionAr": "",
      "price": 204,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80",

    },
    "azura-ice-cream-sandwich": {
      "name": "Azura Ice Cream Sandwich",
      "nameAr": "Azura Ice Cream Sandwich",
      "description": "",
      "descriptionAr": "",
      "price": 189,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&q=80",

    },
    "kinder": {
      "name": "Kinder",
      "nameAr": "Kinder",
      "description": "",
      "descriptionAr": "",
      "price": 219,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&q=80",

    },
    "pistachio": {
      "name": "Pistachio",
      "nameAr": "Pistachio",
      "description": "",
      "descriptionAr": "",
      "price": 255,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80",

    },
    "chocolate-marshmallow": {
      "name": "Chocolate Marshmallow",
      "nameAr": "Chocolate Marshmallow",
      "description": "",
      "descriptionAr": "",
      "price": 199,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&q=80",

    },
    "chocolate-banana": {
      "name": "Chocolate Banana",
      "nameAr": "Chocolate Banana",
      "description": "",
      "descriptionAr": "",
      "price": 179,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80",

    },
    "molten-cake": {
      "name": "Molten Cake",
      "nameAr": "Molten Cake",
      "description": "",
      "descriptionAr": "",
      "price": 178,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&q=80",

    },
    "san-sabastian": {
      "name": "San Sabastian",
      "nameAr": "San Sabastian",
      "description": "",
      "descriptionAr": "",
      "price": 170,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1563805042-7684c019a09d?w=400&q=80",

    },
    "brownies": {
      "name": "Brownies",
      "nameAr": "Brownies",
      "description": "",
      "descriptionAr": "",
      "price": 155,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&q=80",

    },
    "red-velved": {
      "name": "Red Velved",
      "nameAr": "Red Velved",
      "description": "",
      "descriptionAr": "",
      "price": 165,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&q=80",

    },
    "cheese-cake": {
      "name": "Cheese Cake",
      "nameAr": "Cheese Cake",
      "description": "",
      "descriptionAr": "",
      "price": 170,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1563805042-7684c019a09d?w=400&q=80",

    },
    "ice-cream": {
      "name": "Ice Cream",
      "nameAr": "Ice Cream",
      "description": "",
      "descriptionAr": "",
      "price": 55,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&q=80",

    },
    "triple-chocolate": {
      "name": "Triple Chocolate",
      "nameAr": "Triple Chocolate",
      "description": "",
      "descriptionAr": "",
      "price": 159,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&q=80",

    },
    "cookies-cake": {
      "name": "Cookies Cake",
      "nameAr": "Cookies Cake",
      "description": "",
      "descriptionAr": "",
      "price": 165,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80",

    },
    "kinder-cake": {
      "name": "Kinder Cake",
      "nameAr": "Kinder Cake",
      "description": "",
      "descriptionAr": "",
      "price": 165,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&q=80",

    },
    "oreo-cake": {
      "name": "Oreo Cake",
      "nameAr": "Oreo Cake",
      "description": "",
      "descriptionAr": "",
      "price": 165,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&q=80",

    },
    "chocolate-crepe": {
      "name": "Chocolate Crepe",
      "nameAr": "Chocolate Crepe",
      "description": "",
      "descriptionAr": "",
      "price": 212,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&q=80",

    },
    "banana-caramel": {
      "name": "Banana Caramel",
      "nameAr": "Banana Caramel",
      "description": "",
      "descriptionAr": "",
      "price": 180,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&q=80",

    },
    "strawberry-chocolate": {
      "name": "Strawberry Chocolate",
      "nameAr": "Strawberry Chocolate",
      "description": "",
      "descriptionAr": "",
      "price": 189,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&q=80",

    },
    "lotus-crepe": {
      "name": "Lotus Crepe",
      "nameAr": "Lotus Crepe",
      "description": "",
      "descriptionAr": "",
      "price": 195,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80",

    },
    "crepe-brownies": {
      "name": "Crepe Brownies",
      "nameAr": "Crepe Brownies",
      "description": "",
      "descriptionAr": "",
      "price": 229,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80",

    },
    "cheesecake-crepe": {
      "name": "Cheesecake Crepe",
      "nameAr": "Cheesecake Crepe",
      "description": "",
      "descriptionAr": "",
      "price": 239,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&q=80",

    },
    "pistachio-crepe": {
      "name": "Pistachio Crepe",
      "nameAr": "Pistachio Crepe",
      "description": "",
      "descriptionAr": "",
      "price": 219,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1563805042-7684c019a09d?w=400&q=80",

    },
    "azura-crepe": {
      "name": "Azura Crepe",
      "nameAr": "Azura Crepe",
      "description": "",
      "descriptionAr": "",
      "price": 219,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&q=80",

    },
    "mini-chocolate-pancakes": {
      "name": "Mini Chocolate Pancakes",
      "nameAr": "Mini Chocolate Pancakes",
      "description": "",
      "descriptionAr": "",
      "price": 168,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&q=80",

    },
    "mix-for-you": {
      "name": "Mix For You",
      "nameAr": "Mix For You",
      "description": "",
      "descriptionAr": "",
      "price": 198,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1563805042-7684c019a09d?w=400&q=80",

    },
    "chocolate-pancakes": {
      "name": "Chocolate Pancakes",
      "nameAr": "Chocolate Pancakes",
      "description": "",
      "descriptionAr": "",
      "price": 180,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&q=80",

    },
    "brownie-club": {
      "name": "Brownie Club",
      "nameAr": "Brownie Club",
      "description": "",
      "descriptionAr": "",
      "price": 279,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&q=80",

    },
    "mix-berry": {
      "name": "Mix Berry",
      "nameAr": "Mix Berry",
      "description": "",
      "descriptionAr": "",
      "price": 259,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1563805042-7684c019a09d?w=400&q=80",

    },
    "crunchy-lotus": {
      "name": "Crunchy Lotus",
      "nameAr": "Crunchy Lotus",
      "description": "",
      "descriptionAr": "",
      "price": 211,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1563805042-7684c019a09d?w=400&q=80",

    },
    "marshmallow-smores": {
      "name": "Marshmallow S'mores",
      "nameAr": "Marshmallow S'mores",
      "description": "",
      "descriptionAr": "",
      "price": 189,
      "category": "desserts",
      "available": true,
      "image": "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&q=80",

    }
  },
  "drinks": {
    "water": {
      "name": "Water",
      "nameAr": "Water",
      "description": "",
      "descriptionAr": "",
      "price": 29,
      "category": "drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80",

    },
    "pepsi--miranda--seven": {
      "name": "Pepsi- Miranda- Seven",
      "nameAr": "Pepsi- Miranda- Seven",
      "description": "",
      "descriptionAr": "",
      "price": 65,
      "category": "drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1497534446932-c4f89e60f298?w=400&q=80",

    },
    "red-bull": {
      "name": "Red Bull",
      "nameAr": "Red Bull",
      "description": "",
      "descriptionAr": "",
      "price": 115,
      "category": "drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80",

    },
    "fairuz": {
      "name": "Fairuz",
      "nameAr": "Fairuz",
      "description": "",
      "descriptionAr": "",
      "price": 80,
      "category": "drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1497534446932-c4f89e60f298?w=400&q=80",

    },
    "birell": {
      "name": "Birell",
      "nameAr": "Birell",
      "description": "",
      "descriptionAr": "",
      "price": 85,
      "category": "drinks",
      "available": true,
      "image": "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80",

    }
  },
  "shisha": {
    "hookah-mix": {
      "name": "Hookah Mix",
      "nameAr": "Hookah Mix",
      "description": "",
      "descriptionAr": "",
      "price": 180,
      "category": "shisha",
      "available": true,
      "image": "https://images.pexels.com/photos/760280/pexels-photo-760280.jpeg?w=400&q=80",

    },
    "pyrex-hookah": {
      "name": "Pyrex Hookah",
      "nameAr": "Pyrex Hookah",
      "description": "",
      "descriptionAr": "",
      "price": 190,
      "category": "shisha",
      "available": true,
      "image": "https://images.pexels.com/photos/760280/pexels-photo-760280.jpeg?w=400&q=80",

    },
    "luxury-hookah": {
      "name": "Luxury Hookah",
      "nameAr": "Luxury Hookah",
      "description": "",
      "descriptionAr": "",
      "price": 150,
      "category": "shisha",
      "available": true,
      "image": "https://images.pexels.com/photos/760280/pexels-photo-760280.jpeg?w=400&q=80",

    },
    "hookah": {
      "name": "Hookah",
      "nameAr": "Hookah",
      "description": "",
      "descriptionAr": "",
      "price": 65,
      "category": "shisha",
      "available": true,
      "image": "https://images.pexels.com/photos/760280/pexels-photo-760280.jpeg?w=400&q=80",

    },
    "pyrex-twin-hookah": {
      "name": "Pyrex Twin Hookah",
      "nameAr": "Pyrex Twin Hookah",
      "description": "",
      "descriptionAr": "",
      "price": 210,
      "category": "shisha",
      "available": true,
      "image": "https://images.pexels.com/photos/760280/pexels-photo-760280.jpeg?w=400&q=80",

    },
    "azura-hookah": {
      "name": "Azura Hookah",
      "nameAr": "Azura Hookah",
      "description": "",
      "descriptionAr": "",
      "price": 220,
      "category": "shisha",
      "available": true,
      "image": "https://images.pexels.com/photos/760280/pexels-photo-760280.jpeg?w=400&q=80",

    },
    "ice-lay": {
      "name": "Ice Lay",
      "nameAr": "Ice Lay",
      "description": "",
      "descriptionAr": "",
      "price": 30,
      "category": "shisha",
      "available": true,
      "image": "https://images.pexels.com/photos/760280/pexels-photo-760280.jpeg?w=400&q=80",

    },
    "extra": {
      "name": "Extra",
      "nameAr": "Extra",
      "description": "",
      "descriptionAr": "",
      "price": 55,
      "category": "shisha",
      "available": true,
      "image": "https://images.pexels.com/photos/760280/pexels-photo-760280.jpeg?w=400&q=80",

    }
  }
};